package com.ejercicio01.view;

import com.ejercicio01.view.panel.PanelClock;

/**
 *
 * @author mario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCenter = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuitemSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuitemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relojes");
        setMinimumSize(new java.awt.Dimension(800, 600));

        panelCenter.setLayout(new java.awt.GridLayout(2, 2, 1, 1));
        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        menuitemSalir.setText("Salir");
        menuArchivo.add(menuitemSalir);

        menuBar.add(menuArchivo);

        menuAyuda.setText("Ayuda");

        menuitemAcercaDe.setText("AcercaDe");
        menuAyuda.add(menuitemAcercaDe);

        menuBar.add(menuAyuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem menuitemAcercaDe;
    public javax.swing.JMenuItem menuitemSalir;
    public javax.swing.JPanel panelCenter;
    // End of variables declaration//GEN-END:variables
}
