/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ejercicio06.client.view;

/**
 *
 * @author mario
 */
public class Teclado extends javax.swing.JPanel {

    /**
     * Creates new form Teclado
     */
    public Teclado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnParentesisIzq = new javax.swing.JButton();
        btnParentesisDer = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 4));

        btnParentesisIzq.setText("(");
        add(btnParentesisIzq);

        btnParentesisDer.setText(")");
        add(btnParentesisDer);

        btnDel.setText("DEL");
        add(btnDel);

        btnAC.setText("AC");
        add(btnAC);

        btn7.setText("7");
        add(btn7);

        btn8.setText("8");
        add(btn8);

        btn9.setText("9");
        add(btn9);

        btnDivision.setText("/");
        add(btnDivision);

        btn4.setText("4");
        add(btn4);

        btn5.setText("5");
        add(btn5);

        btn6.setText("6");
        add(btn6);

        btnMultiplicacion.setText("x");
        add(btnMultiplicacion);

        btn1.setText("1");
        add(btn1);

        btn2.setText("2");
        add(btn2);

        btn3.setText("3");
        add(btn3);

        btnSuma.setText("+");
        add(btnSuma);

        btn0.setText("0");
        add(btn0);

        btnPunto.setText(".");
        add(btnPunto);

        btnIgual.setText("=");
        add(btnIgual);

        btnResta.setText("-");
        add(btnResta);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn0;
    public javax.swing.JButton btn1;
    public javax.swing.JButton btn2;
    public javax.swing.JButton btn3;
    public javax.swing.JButton btn4;
    public javax.swing.JButton btn5;
    public javax.swing.JButton btn6;
    public javax.swing.JButton btn7;
    public javax.swing.JButton btn8;
    public javax.swing.JButton btn9;
    public javax.swing.JButton btnAC;
    public javax.swing.JButton btnDel;
    public javax.swing.JButton btnDivision;
    public javax.swing.JButton btnIgual;
    public javax.swing.JButton btnMultiplicacion;
    public javax.swing.JButton btnParentesisDer;
    public javax.swing.JButton btnParentesisIzq;
    public javax.swing.JButton btnPunto;
    public javax.swing.JButton btnResta;
    public javax.swing.JButton btnSuma;
    // End of variables declaration//GEN-END:variables
}
