
package com.ejercicio01.view.panel;

/**
 *
 * @author mario
 */
public class PanelClock extends javax.swing.JPanel {

    /**
     * Creates new form PanelClock
     */
    public PanelClock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClock = new javax.swing.JLabel();
        panelSur = new javax.swing.JPanel();
        spHH = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spMM = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spSS = new javax.swing.JSpinner();
        btnModificar = new javax.swing.JButton();
        panelNorte = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 10), new java.awt.Dimension(50, 10), new java.awt.Dimension(20, 32767));
        btnSistema = new javax.swing.JButton();

        setFocusCycleRoot(true);
        setPreferredSize(new java.awt.Dimension(223, 135));
        setLayout(new java.awt.BorderLayout());

        lblClock.setFont(new java.awt.Font("Comic Sans MS", 1, 35)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText("00:00:00");
        lblClock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(lblClock, java.awt.BorderLayout.CENTER);

        spHH.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        spHH.setPreferredSize(new java.awt.Dimension(50, 20));
        panelSur.add(spHH);

        jLabel2.setText(":");
        panelSur.add(jLabel2);

        spMM.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spMM.setPreferredSize(new java.awt.Dimension(50, 20));
        panelSur.add(spMM);

        jLabel3.setText(":");
        panelSur.add(jLabel3);

        spSS.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spSS.setPreferredSize(new java.awt.Dimension(50, 20));
        panelSur.add(spSS);

        btnModificar.setText("Modificar");
        panelSur.add(btnModificar);

        add(panelSur, java.awt.BorderLayout.PAGE_END);

        btnReset.setText("Reset");
        panelNorte.add(btnReset);
        panelNorte.add(filler1);

        btnSistema.setText("Sistema");
        panelNorte.add(btnSistema);

        add(panelNorte, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnReset;
    public javax.swing.JButton btnSistema;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lblClock;
    private javax.swing.JPanel panelNorte;
    private javax.swing.JPanel panelSur;
    public javax.swing.JSpinner spHH;
    public javax.swing.JSpinner spMM;
    public javax.swing.JSpinner spSS;
    // End of variables declaration//GEN-END:variables
}
